"""first setup

Revision ID: 0ca6eb9f1d5c
Revises: 
Create Date: 2022-05-09 14:56:38.442760

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy.dialects.postgresql as sad_psql

# revision identifiers, used by Alembic.
revision = '0ca6eb9f1d5c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    vals, name = ("red", "yellow", "green"), "status_colors"
    sa_enum = sa.Enum(*vals, name=name)
    sa_enum.create(op.get_bind(), checkfirst=True)
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project", sa.Column("status_color", sa_enum, server_default='yellow', nullable=False))
    # op.add_column('project', sa.Column('status_color', sa.Enum('red', 'yellow', 'green', name='status_colors'), server_default='yellow', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    sa_enum = sa.Enum(name='status_colors')
    sa_enum.drop(op.get_bind(), checkfirst=True)
    op.drop_column('project', 'status_color')
    # ### end Alembic commands ###
