"""meeting edit

Revision ID: 2a55dd858502
Revises: 8b29fa84e91d
Create Date: 2022-05-30 15:28:06.730949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a55dd858502'
down_revision = '8b29fa84e91d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('meeting_created_by_fkey', 'meeting', type_='foreignkey')
    op.create_foreign_key(None, 'meeting', 'worker', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'meeting', type_='foreignkey')
    op.create_foreign_key('meeting_created_by_fkey', 'meeting', 'worker', ['created_by'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
