"""meeting id add

Revision ID: 4ab48f7c4ff9
Revises: 2a55dd858502
Create Date: 2022-06-04 18:29:50.527917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ab48f7c4ff9'
down_revision = '2a55dd858502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meeting', sa.Column('id', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meeting', 'id')
    # ### end Alembic commands ###
