"""meeting auto increment

Revision ID: 4cd7d8a2b73e
Revises: e66d7c971573
Create Date: 2022-06-04 20:41:15.578394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cd7d8a2b73e'
down_revision = 'e66d7c971573'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
