"""design edition v1

Revision ID: 50d4e651c714
Revises: 8ac596391756
Create Date: 2022-05-29 19:26:39.251349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50d4e651c714'
down_revision = '8ac596391756'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
