"""project adds

Revision ID: 7c761ceb1d95
Revises: e0b70832d0ea
Create Date: 2022-06-05 23:42:00.406168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c761ceb1d95'
down_revision = 'e0b70832d0ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
