"""Added project_tecjnology table

Revision ID: 7d79d0d9ca7e
Revises: a20d1594714f
Create Date: 2022-05-29 18:45:42.311198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d79d0d9ca7e'
down_revision = 'a20d1594714f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'project', 'dev_team', ['dev_team_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project', type_='foreignkey')
    # ### end Alembic commands ###
