"""design edition

Revision ID: 8ac596391756
Revises: bbb564b296a9
Create Date: 2022-05-29 19:26:13.505014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ac596391756'
down_revision = 'bbb564b296a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
