"""project edit

Revision ID: 8b29fa84e91d
Revises: c134206b6e38
Create Date: 2022-05-30 13:41:40.739997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b29fa84e91d'
down_revision = 'c134206b6e38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('project_customer_id_key', 'project', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('project_customer_id_key', 'project', ['customer_id'])
    # ### end Alembic commands ###
