"""tech edition

Revision ID: bbb564b296a9
Revises: debe7942050e
Create Date: 2022-05-29 19:14:55.823949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbb564b296a9'
down_revision = 'debe7942050e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_technology', sa.Column('completeness', sa.Float(), nullable=False))
    op.alter_column('project_technology', 'dev_team_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('project_technology', 'technology',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_technology', 'technology',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('project_technology', 'dev_team_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('project_technology', 'completeness')
    # ### end Alembic commands ###
