"""design edition v2

Revision ID: c134206b6e38
Revises: 50d4e651c714
Create Date: 2022-05-29 19:27:43.509237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c134206b6e38'
down_revision = '50d4e651c714'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
