"""check

Revision ID: debe7942050e
Revises: 7d79d0d9ca7e
Create Date: 2022-05-29 19:02:09.648218

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'debe7942050e'
down_revision = '7d79d0d9ca7e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_technology', sa.Column('technology', sa.String(), nullable=True))
    op.drop_constraint('project_technology_customer_id_key', 'project_technology', type_='unique')
    op.drop_constraint('project_technology_customer_id_fkey', 'project_technology', type_='foreignkey')
    op.drop_column('project_technology', 'cost')
    op.drop_column('project_technology', 'status_color')
    op.drop_column('project_technology', 'customer_id')
    op.drop_column('project_technology', 'name')
    op.drop_column('project_technology', 'status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_technology', sa.Column('status', sa.VARCHAR(), server_default=sa.text("'Project initialization'::character varying"), autoincrement=False, nullable=True))
    op.add_column('project_technology', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('project_technology', sa.Column('customer_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('project_technology', sa.Column('status_color', postgresql.ENUM('red', 'yellow', 'green', name='status_colors'), server_default=sa.text("'yellow'::status_colors"), autoincrement=False, nullable=False))
    op.add_column('project_technology', sa.Column('cost', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('project_technology_customer_id_fkey', 'project_technology', 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint('project_technology_customer_id_key', 'project_technology', ['customer_id'])
    op.drop_column('project_technology', 'technology')
    # ### end Alembic commands ###
