"""project_technology adds

Revision ID: e0b70832d0ea
Revises: 4cd7d8a2b73e
Create Date: 2022-06-05 23:20:21.783693

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e0b70832d0ea'
down_revision = '4cd7d8a2b73e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_design', 'completeness',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.add_column('project_technology', sa.Column('project_id', sa.INTEGER(), nullable=False))
    op.alter_column('project_technology', 'completeness',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.create_foreign_key(None, 'project_technology', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_column('project_technology', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_technology', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'project_technology', type_='foreignkey')
    op.alter_column('project_technology', 'completeness',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('project_technology', 'project_id')
    op.alter_column('project_design', 'completeness',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###
