"""project_workers add

Revision ID: e66d7c971573
Revises: 4ab48f7c4ff9
Create Date: 2022-06-04 18:35:47.911023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e66d7c971573'
down_revision = '4ab48f7c4ff9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('project_workers_worker_id_fkey', 'project_workers', type_='foreignkey')
    op.drop_constraint('project_workers_project_id_fkey', 'project_workers', type_='foreignkey')
    op.create_foreign_key(None, 'project_workers', 'worker', ['worker_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'project_workers', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_workers', type_='foreignkey')
    op.drop_constraint(None, 'project_workers', type_='foreignkey')
    op.create_foreign_key('project_workers_project_id_fkey', 'project_workers', 'project', ['project_id'], ['id'])
    op.create_foreign_key('project_workers_worker_id_fkey', 'project_workers', 'worker', ['worker_id'], ['id'])
    # ### end Alembic commands ###
